on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manual trigger for GitHub API data fetch'
        required: true
        default: 'true'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get github data
        uses: actions/checkout@v4
      - name: Run script with secret
        env:
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
        run: |
          cd website
          node -e 'import("./src/routes/gh-data").then(module => module.fetchAllData())'
          "
      - name: Deploy
        run: npm run deploy
