on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manual trigger for GitHub API data fetch'
        required: true
        default: 'true'
  schedule:
    - cron: '45 * * * *'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get github data
        uses: actions/checkout@v4
      - name: Run script with secret
        env:
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
        run: |
          cd website
          npm install
          npm run build
          npm run update-gh-data
          git config --global user.name 'nabrams'
          git config --global user.email 'nabrams94@gmail.com'
          cd .. && git add . && git commit -m "Update GitHub data" && git push
