name: Manual Dispatch
on:
  workflow_dispatch:

jobs:
  dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger existing workflow
        uses: actions/github-script@v4
        with:
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'get-github-api-data.yml',
              ref: 'main'
            });
